name: subs-manager
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run worker
    env_file: ../.env
    depends_on:
      - redis
